In [12]:
import numpy as np

# 행렬의 선언

numpy.array: 파이썬 리스트나 튜플을 사용하여 배열을 생성합니다.

In [13]:
# 리스트로부터 배열 생성
arr1 = np.array([1, 2, 3])
print(arr1)  


[1 2 3]


In [14]:
# 중첩 리스트로부터 2차원 배열 생성
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr3)
print("Shape: ", arr3.shape)
print("Data type: ", arr3.dtype)
print("Size: ", arr3.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Data type:  int64
Size:  9


numpy.zeros: 모든 요소가 0인 배열을 생성합니다.

In [16]:
# 2x3 배열 생성
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


numpy.ones: 모든 요소가 1인 배열을 생성합니다.


In [17]:
# 3x2 배열 생성
arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


numpy.eye: 단위 행렬(identity matrix)을 생성합니다.

In [18]:
# 3x3 단위 행렬 생성
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy.arange: 지정된 범위 내의 값을 가진 배열을 생성합니다.

In [19]:
# 0부터 9까지의 정수를 가진 배열 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


numpy.linspace: 지정된 범위 내에서 균일한 간격으로 값을 가진 배열을 생성합니다.

In [20]:
# 0부터 1까지의 범위에서 5개의 값을 가진 배열 생성
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


numpy.random: 난수를 사용하여 배열을 생성합니다.

In [21]:
# 0부터 1까지의 범위에서 무작위 값으로 채워진 2x3 배열 생성
arr = np.random.random((2, 3))
print(arr)

[[0.63780628 0.55322144 0.92134357]
 [0.62657691 0.75903074 0.65072541]]


# 행렬의 곱셈

numpy.dot(행렬1, 행렬2)

In [22]:
# 2x3 행렬 A와 3x2 행렬 B를 생성합니다.
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# 행렬 A와 B를 곱합니다.
C = np.dot(A, B)

# 결과를 출력합니다.
print(C)

[[ 58  64]
 [139 154]]
